"""OCR artifact generation."""

from .checkpoint import (
    CheckpointArtifactPaths,
    publish_checkpoint,
    resolve_checkpoint_bundle,
    restore_checkpoint,
    restore_checkpoint_history,
    verify_checkpoint_bundle,
)
from .detector_only import (
    DetectorOnlyError,
    DetectorPolygon,
    PaddleOcrV6Detector,
    identity_from_locked_config,
    parse_detector_output,
    runtime_identity_from_config,
    verify_detector_only,
    verify_runtime_identity,
)
from .frame_snapshot import CanonicalFrameError, CanonicalFrameSnapshot, decode_canonical_frame
from .geometry import CropConfig, CropGeometryError, encode_crop, reconstruct_crop
from .phase1 import (
    Phase1Identity,
    canonical_config_sha256,
    run_detect_crop,
    run_representative_selection,
    run_tracking,
    validate_frame_sources,
    verify_detection_artifact,
    verify_linked_artifacts,
    verify_tracking_artifact,
)
from .pipeline import EasyOcrReader, extract_ocr_frames, normalize_vietnamese_text
from .ppocrv6 import PaddleOcrV6Error, PaddleOcrV6Reader, verify_ppocrv6
from .quality_gate import (
    DetectionQualityConfig,
    ExecutionAttestation,
    GroundTruthFrame,
    GroundTruthInstance,
    NegativeFixture,
    NegativeSuiteReceipt,
    enforce_quality_thresholds,
    evaluate_detection_quality,
    load_and_verify_execution_attestation,
    load_ground_truth_manifest,
    verify_file_unchanged,
    verify_negative_fixture_suite,
    verify_negative_suite_receipt,
)
from .sharding import (
    OcrShardArtifactBundle,
    plan_frame_shards,
    verify_global_shard_structure,
    verify_global_shards,
)
from .tracking import TrackingConfig, build_trajectories, select_representatives

__all__ = [
    "EasyOcrReader",
    "CropConfig",
    "CropGeometryError",
    "DetectorOnlyError",
    "DetectorPolygon",
    "DetectionQualityConfig",
    "ExecutionAttestation",
    "GroundTruthFrame",
    "GroundTruthInstance",
    "identity_from_locked_config",
    "CanonicalFrameError",
    "CanonicalFrameSnapshot",
    "CheckpointArtifactPaths",
    "PaddleOcrV6Error",
    "PaddleOcrV6Detector",
    "OcrShardArtifactBundle",
    "NegativeFixture",
    "NegativeSuiteReceipt",
    "Phase1Identity",
    "PaddleOcrV6Reader",
    "extract_ocr_frames",
    "encode_crop",
    "enforce_quality_thresholds",
    "evaluate_detection_quality",
    "canonical_config_sha256",
    "build_trajectories",
    "normalize_vietnamese_text",
    "parse_detector_output",
    "decode_canonical_frame",
    "reconstruct_crop",
    "load_and_verify_execution_attestation",
    "load_ground_truth_manifest",
    "run_detect_crop",
    "run_representative_selection",
    "run_tracking",
    "runtime_identity_from_config",
    "select_representatives",
    "TrackingConfig",
    "verify_detection_artifact",
    "verify_detector_only",
    "verify_runtime_identity",
    "verify_linked_artifacts",
    "verify_tracking_artifact",
    "verify_negative_fixture_suite",
    "verify_negative_suite_receipt",
    "verify_file_unchanged",
    "validate_frame_sources",
    "plan_frame_shards",
    "publish_checkpoint",
    "resolve_checkpoint_bundle",
    "restore_checkpoint",
    "restore_checkpoint_history",
    "verify_global_shard_structure",
    "verify_global_shards",
    "verify_checkpoint_bundle",
    "verify_ppocrv6",
]
