"""Phase 4 Test: Stage 2 Task-Specific Precision Layer (KIS, VQA, TRAKE).

Runs Stage 2 on all 3 competition test queries:
1. KIS: BGE-Reranker-v2-m3 Cross-Encoder + Heuristic Scoring layer.
2. VQA: Cross-Encoder + Extractive LLM Answer Reader for Top 1 frame.
3. TRAKE: Dynamic Programming Monotonic Path Finder across E1-E4.
"""

from __future__ import annotations

import logging
from typing import Any

from online.src.contracts.query import ParsedQuery
from online.src.retrieval.embeddings import ModelRegistry
from online.src.retrieval.fusion import MultimodalFusionEngine
from online.src.retrieval.query_parser import QueryParser
from online.src.retrieval.stage2_reranker import Stage2Reranker
from online.src.retrieval.vector_search import FastVectorSearchEngine
from online.src.retrieval.vqa_reasoner import VQAReasoner

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def print_kis_results(reranked_pool: list[dict[str, Any]], raw_query: str):
    print(f"\n{'='*105}")
    print(f"🎯 TASK 1: KNOWN-ITEM SEARCH (KIS) — FINAL STAGE 2 RANKINGS")
    print(f"📝 Raw Query: \"{raw_query}\"")
    print(f"⚖️ Pipeline: RRF Fusion → BGE Cross-Encoder → Heuristic Scoring")
    print(f"{'='*105}")

    print("\n### 📋 Official Submission Candidate List (Top 10)")
    print("| Final Rank | Official Submission String | Frame Index | Time (s) | Stage 1 (Norm) | BGE-Reranker Score | Final Heuristic Score | Image Path (AIC Relative) |")
    print("|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---|")
    for r in reranked_pool[:10]:
        print(
            f"| **{r['final_rank']}** | `{r['submission_string']}` | `{r['frame_idx']}` | {r['pts_time_s']}s | "
            f"`{r['normalized_score']*100:.1f}%` | `{r['cross_encoder_score']:.4f}` | **{r['final_score']:.4f}** | `{r['image_relpath']}` |"
        )

    # Top 1 Explainability Card
    top1 = reranked_pool[0]
    print(f"\n{'─'*105}")
    print(f"🌟 TOP 1 FRAME EXPLAINABILITY DOSSIER CARD (KIS)")
    print(f"{'─'*105}")
    print(f"• Video ID: `{top1['video_id']}` | Frame Index: `{top1['frame_idx']}` | Timestamp: `{top1['pts_time_s']}s`")
    print(f"• Official Submission String: `{top1['submission_string']}`")
    print(f"• Local Keyframe Image Path: `{top1['image_relpath']}`")
    print(f"• Stage 1 RRF Score: `{top1['stage1_score']:.6f}` (Active Modalities: {top1['active_channels']}/3, Synergy: {top1['synergy_multiplier']}x)")
    print(f"• BGE Cross-Encoder Confidence: `{top1['cross_encoder_score']:.4f}` (Raw Relevance)")
    print(f"• Final Heuristic Score: `{top1['final_score']:.4f}`")
    print(f"• Heuristic Breakdown: `{top1.get('heuristic_breakdown', 'n/a')}`")
    print(f"• DAM Visual Entities: \"{top1.get('dam_summary') or 'N/A'}\"")
    if top1.get("matched_boxes"):
        boxes_str = "; ".join([f"{b['class_entity']} (Sim: {b['score']}, BBox: {b['bbox']})" for b in top1["matched_boxes"]])
        print(f"• Matched Bounding Boxes: {boxes_str}")
    print(f"• Spoken Speech (ASR): \"{top1.get('asr_transcript') or '(No speech / music)'}\"")
    print(f"{'─'*105}\n")


def print_vqa_results(vqa_pool: list[dict[str, Any]], raw_query: str):
    print(f"\n{'='*105}")
    print(f"❓ TASK 2: VISUAL QUESTION ANSWERING (VQA) — FINAL STAGE 2 RESULTS")
    print(f"📝 Raw Query: \"{raw_query}\"")
    print(f"{'='*105}")

    print("\n### 📋 Official Submission Candidate List (Top 10)")
    print("| Final Rank | Official Submission String | Frame Index | Time (s) | Extracted VQA Answer | Cross-Encoder Score | Final Score | Image Path |")
    print("|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---|")
    for r in vqa_pool[:10]:
        print(
            f"| **{r['final_rank']}** | `{r['submission_string']}` | `{r['frame_idx']}` | {r['pts_time_s']}s | "
            f"**\"{r.get('vqa_answer', '')}\"** | `{r['cross_encoder_score']:.4f}` | **{r['final_score']:.4f}** | `{r['image_relpath']}` |"
        )

    top1 = vqa_pool[0]
    print(f"\n{'─'*105}")
    print(f"🌟 TOP 1 EVIDENCE FRAME EXPLAINABILITY DOSSIER CARD (VQA)")
    print(f"{'─'*105}")
    print(f"• Extracted VQA Answer: **\"{top1.get('vqa_answer', '')}\"** (Generated by Gemini Flash Extractive Reader)")
    print(f"• Official Submission String: `{top1['submission_string']}`")
    print(f"• Video ID: `{top1['video_id']}` | Frame Index: `{top1['frame_idx']}` | Timestamp: `{top1['pts_time_s']}s`")
    print(f"• Local Keyframe Image Path: `{top1['image_relpath']}`")
    print(f"• Final Blended Score: `{top1['final_score']:.4f}` (Stage 1: {top1['stage1_score']:.6f}, Cross-Encoder: {top1['cross_encoder_score']:.4f})")
    print(f"• Spoken Transcript Context: \"{top1.get('asr_transcript') or 'N/A'}\"")
    print(f"• DAM Visual Summary: \"{top1.get('dam_summary') or 'N/A'}\"")
    print(f"{'─'*105}\n")


def print_trake_results(trake_sequences: list[dict[str, Any]], raw_query: str):
    print(f"\n{'='*105}")
    print(f"⏱️ TASK 3: TEMPORAL ACTION KEYFRAME EXTRACTION (TRAKE) — DYNAMIC PROGRAMMING SEQUENCES")
    print(f"📝 Raw Sequence Query: \"{raw_query}\"")
    print(f"🔒 Constraint: Strict Monotonicity t(f1) < t(f2) < t(f3) < t(f4) within same video")
    print(f"{'='*105}")

    print("\n### 📋 Official Submission Candidate Sequences")
    if trake_sequences:
        print("| Rank | Official Submission String | Video ID | Matched Frames (E1 -> E4) | Timestamps (s) | Monotonic? | Sequence DP Score |")
        print("|:---:|:---:|:---:|:---:|:---:|:---:|:---:|")
        for s in trake_sequences[:10]:
            frames_str = " -> ".join(map(str, s['matched_frames']))
            times_str = " -> ".join([f"{t:.1f}s" for t in s['timestamps']])
            is_mono = all(s['timestamps'][i] < s['timestamps'][i+1] for i in range(len(s['timestamps'])-1))
            mono_icon = "✅ YES" if is_mono else "❌ NO"
            print(
                f"| **{s['rank']}** | `{s['submission_string']}` | `{s['video_id']}` | `{frames_str}` | "
                f"`{times_str}` | {mono_icon} | **{s['sequence_score']:.6f}** |"
            )

        top1 = trake_sequences[0]
        print(f"\n{'─'*105}")
        print(f"🌟 TOP 1 SEQUENCE EXPLAINABILITY DOSSIER CARD (TRAKE)")
        print(f"{'─'*105}")
        print(f"• Video ID: `{top1['video_id']}`")
        print(f"• Official Submission String: `{top1['submission_string']}`")
        print(f"• Sequence DP Score: `{top1['sequence_score']:.6f}`")
        for i, ev in enumerate(top1.get("event_dossiers", []), 1):
            print(f"   ► Event E{i}: Frame `{ev['frame_idx']}` at `{ev['pts_time_s']:.1f}s` | Image: `{ev['image_relpath']}` | Vis Sim: `{ev.get('score_vis', 0.0):.3f}`")
        print(f"{'─'*105}\n")
    else:
        print("*(No valid multi-event monotonic sequences found across candidates with current branch pool)*")


def main():
    searcher = FastVectorSearchEngine()
    registry = ModelRegistry.get_instance()
    fusion_engine = MultimodalFusionEngine(searcher=searcher, registry=registry, k_rrf=60)
    vqa_reasoner = VQAReasoner(gemini_model_id="gemini-3.6-flash")
    stage2_reranker = Stage2Reranker(registry=registry, vqa_reasoner=vqa_reasoner)
    parser = QueryParser(gemini_model_id="gemini-3.6-flash")

    # ──────────────────────────────────────────────────────────────────────────
    # Task 1: KIS Test
    # ──────────────────────────────────────────────────────────────────────────
    raw_kis = "Tìm một đoạn video đua xe đạp, góc quay từ flycam trên cao, một vận động viên mặc áo xanh dương, trắng đang vượt ba vận động viên khác và lên vị trí dẫn đầu. Biết sau đó vận động viên này dẫn đầu suốt đoạn đường còn lại đến đích."
    parsed_kis = parser.parse(raw_kis, task_type="KIS", engine="gemini")
    kis_s1 = fusion_engine.retrieve_and_fuse(parsed_kis, top_k_pool=50, branch_limit=500)
    kis_s2 = stage2_reranker.rerank_kis(parsed_kis, kis_s1, final_top_k=20)
    print_kis_results(kis_s2, raw_kis)

    # ──────────────────────────────────────────────────────────────────────────
    # Task 2: VQA Test
    # ──────────────────────────────────────────────────────────────────────────
    raw_vqa = "Đoạn video về một người phụ nữ dạy nấu ăn cho những người khác. Trong đoạn video có thể thấy một người đang cầm công thức món ăn với nguyên liệu chính là 200g thịt nạc xay. Hỏi tiêu đề của công thức nấu ăn (tên món ăn) này là gì?"
    parsed_vqa = parser.parse(raw_vqa, task_type="VQA", engine="gemini")
    vqa_s1 = fusion_engine.retrieve_and_fuse(parsed_vqa, top_k_pool=50, branch_limit=500)
    vqa_s2 = stage2_reranker.rerank_vqa(parsed_vqa, vqa_s1, final_top_k=20)
    print_vqa_results(vqa_s2, raw_vqa)

    # ──────────────────────────────────────────────────────────────────────────
    # Task 3: TRAKE Test
    # ──────────────────────────────────────────────────────────────────────────
    raw_trake = """E1: Khoảnh khắc đầu tiên bột được bỏ vào tô măng tây.
E2: Khoảnh khắc đầu tiên thấy miến măng tây đầu tiên tiếp xúc với dầu trong chảo.
E3: Khoảnh khắc miếng măng tây đầu tiên rời khỏi chảo dầu.
E4: Khoảng khắc miếng măng tây cuối cùng rời chảo dầu và nằm hoàn toàn trên dĩa."""
    parsed_trake = parser.parse(raw_trake, task_type="TRAKE", engine="gemini")
    event_queries = []
    event_pools = []
    for ev in parsed_trake.trake_events:
        sub_parsed = ParsedQuery(
            task_type="KIS",
            original_query=ev.description,
            global_scene_en=ev.scene_en,
            objects_en=ev.objects_en,
            speech_vi=ev.speech_vi,
            ocr_keywords=ev.ocr_keywords,
            weights={"vis": 0.45, "dam": 0.40, "asr": 0.15, "ocr": 0.00},
        )
        event_queries.append(sub_parsed)
        pool = fusion_engine.retrieve_and_fuse(sub_parsed, top_k_pool=100, branch_limit=500)
        event_pools.append(pool)

    trake_sequences = stage2_reranker.solve_trake_video_guided_dp(
        event_queries=event_queries,
        candidate_pools=event_pools,
        searcher=searcher,
        top_n_videos=10,
        final_top_k=10,
    )
    print_trake_results(trake_sequences, raw_trake)


if __name__ == "__main__":
    main()
