"""Versioned cross-team data contracts."""

from .asr import AsrKeyframeRef, AsrSegmentRecord, AsrVideoManifest
from .models import (
    CaptionResult,
    DetectorMetadata,
    FrameRef,
    MaskRLE,
    ObjectFrameRecord,
    ObjectRegion,
    RunManifest,
    SegmentationResult,
)
from .ocr import LegacyOcrFrameRecord, OcrError, OcrFrameRecord, OcrText
from .ocr_phase1 import (
    CropProvenance,
    OcrCheckpointArtifact,
    OcrCheckpointCounts,
    OcrCheckpointFile,
    OcrDetection,
    OcrDetectionFrameRecord,
    OcrFrameShard,
    OcrGlobalShardManifest,
    OcrGlobalShardReceipt,
    OcrPhase1Checkpoint,
    OcrPhase1Receipt,
    OcrTrajectoryRecord,
    QuadGeometry,
    RawQuadGeometry,
    RepresentativeCropBinding,
    TrajectoryMember,
)
from .query import AnswerSource, QueryEvent, QuerySpec, TaskType, TemporalOperator
from .scene_embedding import SCENE_EMBEDDING_SCHEMA, SceneEmbeddingRecord

__all__ = [
    "SCENE_EMBEDDING_SCHEMA",
    "AnswerSource",
    "AsrKeyframeRef",
    "AsrSegmentRecord",
    "AsrVideoManifest",
    "CaptionResult",
    "DetectorMetadata",
    "FrameRef",
    "LegacyOcrFrameRecord",
    "MaskRLE",
    "ObjectFrameRecord",
    "ObjectRegion",
    "OcrError",
    "OcrDetection",
    "OcrDetectionFrameRecord",
    "OcrFrameShard",
    "OcrGlobalShardManifest",
    "OcrGlobalShardReceipt",
    "OcrFrameRecord",
    "OcrPhase1Receipt",
    "OcrCheckpointArtifact",
    "OcrCheckpointCounts",
    "OcrCheckpointFile",
    "OcrPhase1Checkpoint",
    "OcrText",
    "OcrTrajectoryRecord",
    "QueryEvent",
    "QuerySpec",
    "RunManifest",
    "QuadGeometry",
    "RawQuadGeometry",
    "RepresentativeCropBinding",
    "SceneEmbeddingRecord",
    "SegmentationResult",
    "TaskType",
    "TrajectoryMember",
    "CropProvenance",
    "TemporalOperator",
]
